#!/usr/bin/python3
def factorize(n):
    i = 2
    while i <= n:
        if n % i == 0:
            print(f"{n} = {n // i} * {i}")
            return
        i += 1

import sys

if len(sys.argv) != 2:
    print("Usage: python factors.py <file>")
    sys.exit(1)

with open(sys.argv[1]) as f:
    for line in f:
        n = int(line.strip())
        if n > 1:
            factorize(n)
